In [ ]:
'''
 step02_indexing 관련문제
 문) 6행6열의 다차원 zero 행렬 객체를 생성한 후 다음과 같이  단계별로 indexing 하시오.
   단계1 : 36개의 셀에 1~36까지 정수 채우기
   단계2 : 2번째 행 전체 원소 출력하기  
              출력 결과 : 7.   8.   9.  10.  11.  12.
   단계3 : 5번째 열 전체 원소 출력하기 
              출력결과 : 5. 11. 17. 23. 29. 35.            
   단계4 : 15~29까지 블럭으로 출력하기
              출력결과 :  
       15.  16.  17.
       21.  22.  23
       27.  28.  29. 
 
<<출력 예시>>
단계1 : 36개의 셀에 1~36까지 정수 채우기 
[[  1.   2.   3.   4.   5.   6.]
 [  7.   8.   9.  10.  11.  12.]
 [ 13.  14.  15.  16.  17.  18.]
 [ 19.  20.  21.  22.  23.  24.]
 [ 25.  26.  27.  28.  29.  30.]
 [ 31.  32.  33.  34.  35.  36.]]
 
단계2 :첫번째 행 전체 원소 출력
[ 1.  2.  3.  4.  5.  6.]

단계3 :5번째 열 전체 원소 출력하기 
[  5.  11.  17.  23.  29.  35.]

단계4 :15~29까지 블럭으로 출력하기
[[ 15.  16.  17.]
 [ 21.  22.  23.]
 [ 27.  28.  29.]]
'''

In [2]:
import numpy as np

zarr = np.zeros( (6, 6)  ) 

zarr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [3]:
# 단계1 : 36개의 셀에 1~36까지 정수 채우기 
cnt = 0
for i in np.arange(6) : # 행 index
    for j in np.arange(6) : # 열 index
        cnt += 1
        zarr[i, j] = cnt
    
print(zarr)  

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]
 [13. 14. 15. 16. 17. 18.]
 [19. 20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29. 30.]
 [31. 32. 33. 34. 35. 36.]]


In [4]:

# 단계2 :첫번째 행 전체 원소 출력   
zarr[0]    

array([1., 2., 3., 4., 5., 6.])

In [5]:
    
# 단계3 :5번째 열 전체 원소 출력하기    
zarr[:,4]

array([ 5., 11., 17., 23., 29., 35.])

In [6]:
# 단계4 :15~29까지 블럭으로 출력하기    
zarr[2:5, 2:5]    
    

array([[15., 16., 17.],
       [21., 22., 23.],
       [27., 28., 29.]])