In [ ]:
'''
step03_reshape 관련문제
문) 다음과 같이  단계별로 자료구조를 생성하시오.
    단계1 : 1~84 정수를  이용하여 벡터 생성
    단계2 : 벡터를 대상으로 7x3x4 구조의 3차원 배열로 모양 변경
    단계3 : 3차원 배열을 대상으로 (행,면,열) 축의 순서로 구조 변경
'''

In [1]:
import numpy as np

# 1. vector 생성 
arr1d = np.arange(1, 85)
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84])

In [2]:
# 2. 3차원 배열 
arr3d = arr1d.reshape(7, 3, 4)
arr3d.shape 

(7, 3, 4)

In [3]:
# 3. transpose(행,면,열)
arr3d_tran = arr3d.transpose(1,0,2)
print(arr3d_tran)
arr3d_tran.shape # (3, 7, 4)

[[[ 1  2  3  4]
  [13 14 15 16]
  [25 26 27 28]
  [37 38 39 40]
  [49 50 51 52]
  [61 62 63 64]
  [73 74 75 76]]

 [[ 5  6  7  8]
  [17 18 19 20]
  [29 30 31 32]
  [41 42 43 44]
  [53 54 55 56]
  [65 66 67 68]
  [77 78 79 80]]

 [[ 9 10 11 12]
  [21 22 23 24]
  [33 34 35 36]
  [45 46 47 48]
  [57 58 59 60]
  [69 70 71 72]
  [81 82 83 84]]]


(3, 7, 4)