In [1]:
"""
1. 축(axis) : 행축, 열축 
# 행축은 동일한 열들의 모임(첫번째 행축의 평균은 첫번째 열의 평균이 된다)
# 열축은 동일한 행들의 모임(첫번째 열축의 평균은 첫번째 행의 평균이 된다)
2. 행렬곱 연산 : dot(x, y)

 회귀분석에서 행렬곱 예 
  - 예측치(y) = [입력(x) * 기울기(a)] + 절편(b)
 신경망에서 행렬곱 예
  - 은닉층(h) = [입력(x) * 가중치(w)] + 편향(b)
"""
import numpy as np

# 1. 축(axis) : 행축, 열축 : ppt(56)
'''
행축 : 동일한 열들의 모음(열 단위)
열축 : 동일한 행들의 모음(행 단위)
'''

arr = np.arange(1,21).reshape(5,4)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [2]:
print('행축 합계 = ', arr.sum(axis = 0)) # 열 단위 
print('열축 합계 =', arr.sum(axis = 1)) # 행 단위 
print('전체 합계 =', arr.sum()) # 전체 합계  = 210
#=> 판다스는 axis를 생략하면 axis=0가 디폴트 기본값이 된다

행축 합계 =  [45 50 55 60]
열축 합계 = [10 26 42 58 74]
전체 합계 = 210


In [3]:
# 2. 행렬곱 : np.dot(x, y) : ppt(57)
x = np.array([[1,1], [0,1]])
y = np.array([[2,3], [1,5]])
print(x.shape) # (2, 2)
print(y.shape) # (2, 2)

(2, 2)
(2, 2)


In [4]:
'''
행렬곱 연산 전제조건 
1. x,y 모두 행렬
2. 수 일치 : x(열) = y(행)
'''
# 수 일치 : x(열) = y(행)
z = np.dot(x, y)
print(z) # 3 = (1*2) + (1*1)

[[3 8]
 [1 5]]


In [5]:
# [실습1] 신경망(ppt.30) 입력의 열 가중치 행 값 같아야댐
x = np.array([[0.1, 0.2]])
x.shape # (1, 2)- > 2차원 데이터

(1, 2)

In [6]:
w = np.array([[1,2], [2,3]])
w.shape # (2, 2)- > 2차원 데이터

(2, 2)

In [7]:
h = np.dot(x, w)
print(h) # [[0.5, 0.8]]
h.shape # (1, 2)

[[0.5 0.8]]


(1, 2)

In [8]:
# [실습2]
x = np.array([[0.1,0.2], [0.3,0.4]])
w = np.array([[1,2,3], [2,3,4]])
print(x.shape) # (2, 2)
w.shape # (2, 3)

(2, 2)


(2, 3)

In [9]:
h = np.dot(x, w)
print(h.shape) # (2, 3)
h

(2, 3)


array([[0.5, 0.8, 1.1],
       [1.1, 1.8, 2.5]])