In [1]:
"""
numpy indexing
 - indexing/slicing
 - 1차원 indexing : list 동일 
 - 2, 3차원 indexing 
 - boolean indexing
"""
import numpy as np
'''
1차원 : obj[index]
2차원 : obj[행index, 열index] - 행 index : default
3차원 : obj[면index, 행index, 열index] - 면index : default
'''

# 1. indexing 

# 1) list 객체 
lst = [0,1,2,3,4,5]
print(lst[3]) # 4번째 원소 
print(lst[:]) # 전체 원소 
print(lst[:3]) # 범위 

3
[0, 1, 2, 3, 4, 5]
[0, 1, 2]


In [2]:
# 2) numpy 객체 
arr = np.arange(10) # 0 ~ 9
print(arr) 
print(arr[3])
print(arr[:])
print(arr[:3])

[0 1 2 3 4 5 6 7 8 9]
3
[0 1 2 3 4 5 6 7 8 9]
[0 1 2]


In [3]:
# 2. slicing
arr_sl = arr[5:8]
arr_sl 

array([5, 6, 7])

In [4]:
# 블록 수정 : list 불가능 
arr_sl[:] = 500 # 사본 수정 
arr_sl 

array([500, 500, 500])

In [5]:
# 원본도 수정 
arr 

array([  0,   1,   2,   3,   4, 500, 500, 500,   8,   9])

In [6]:
# 3. 2차원, 3차원 indexing 
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d.shape #  (3, 3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# 행 접근 : obj[행index]
print(arr2d[0]) # [1,2,3]
# 열 접근 : obj[행index, 열index]
print(arr2d[:, 1]) # [2, 5, 8]
# box 참조 
arr2d[1:,1:]

[1 2 3]
[2 5 8]


array([[5, 6],
       [8, 9]])

In [9]:
arr3d = np.array([ [[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
arr3d.shape # (2, 2, 3) : 2면2행3열

(2, 2, 3)

In [11]:
# 면 접근 
print(arr3d[1]) # 2면 참조 
# 행 접근 
print(arr3d[1,1]) # 2면2행 참조 
# 열 접근 
print(arr3d[1,1,1]) # 2면2행2열 참조 : 11

[[ 7  8  9]
 [10 11 12]]
[10 11 12]
11


In [12]:
# 4. boolean indexing : obj[조건식]
data = np.random.randn(3, 4)
print(data)


[[-0.4648679  -1.30138658  0.65556144  0.2824092 ]
 [ 0.54541069  0.57685875 -0.10184915  0.8465687 ]
 [ 0.28774385 -1.10812228  0.36303934  0.48374005]]


In [13]:
# 0.5이상 
data2 = data[data >= 0.5]
data2 # [1.58643286, 1.66472975]

array([0.65556144, 0.54541069, 0.57685875, 0.8465687 ])

In [14]:
# 0.1 ~ 0.5 : 범위 
#data3 = data[data >= 0.1 and data <= 0.5] # Error 
# logical_and() 이용 
data[np.logical_and(data >= 0.1, data <= 0.5)]

array([0.2824092 , 0.28774385, 0.36303934, 0.48374005])

In [ ]:
'''
numpy 논리식 함수 
np.logical_and() : and 
np.logical_or() : or
np.logical_xor() : xor
np.logical_not() : not
'''