In [2]:
"""
sparse matrix 작업 절차 
 1. csv file load : temp_spam_data2.csv
 2. texts(x), target(y) 전처리 
 3. max features 
 4. sparse matrix
"""

import string # text 전처리 
# sparse matrix
from sklearn.feature_extraction.text import TfidfVectorizer 
import pandas as pd # csv file 


# 1. csv file load
spam_data = pd.read_csv("C:/Users/hyebin/Desktop/study/python_ML/data/textMining_data/temp_spam_data2.csv",
            header = None, encoding='utf-8')
spam_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5574 entries, 0 to 5573
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       5574 non-null   object
 1   1       5574 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [3]:
# 2. texts(x), target(y) 전처리 
target = spam_data[0] # 1번칼럼 
texts = spam_data[1] # 2번칼럼 

print(target) # ham(0) vs spam(1)
print(texts)

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5569    spam
5570     ham
5571     ham
5572     ham
5573     ham
Name: 0, Length: 5574, dtype: object
0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5569    This is the 2nd time we have tried 2 contact u...
5570                  Will  b going to esplanade fr home?
5571    Pity, * was in mood for that. So...any other s...
5572    The guy did some bitching but I acted like i'd...
5573                           Rofl. Its true to its name
Name: 1, Length: 5574, dtype: object


In [7]:
# 1) target -> dummy 생성 
target = [1 if t == 'spam' else 0 for t in target]
target [:50]# [0, 1, 0, 1, 0]

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [9]:
# 2) texts 전처리 : 숫자, 특수문자, 공백 제거 
def text_prepro(texts):
    # Lower case
    texts = [x.lower() for x in texts]
    # Remove punctuation
    texts = [''.join(c for c in x if c not in string.punctuation) for x in texts]
    # Remove numbers
    texts = [''.join(c for c in x if c not in string.digits) for x in texts]
    # Trim extra whitespace
    texts = [' '.join(x.split()) for x in texts]
    return texts

# 함수 호출 : texts 전처리 
texts = text_prepro(texts)   
print(texts[:5])

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat', 'ok lar joking wif u oni', 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry questionstd txt ratetcs apply overs', 'u dun say so early hor u c already then say', 'nah i dont think he goes to usf he lives around here though']


In [15]:
# 3. max features 
'''
tfidf = TfidfVectorizer()
tfidf_fit = tfidf.fit(texts) # texts -> words 
'''
tfidf_fit = TfidfVectorizer().fit(texts)
voc = tfidf_fit.vocabulary_ # 단어 반환 
print(voc)
len(voc) # 8603

{'go': 2873, 'until': 7839, 'jurong': 3780, 'point': 5547, 'crazy': 1567, 'available': 491, 'only': 5130, 'in': 3492, 'bugis': 952, 'great': 2969, 'world': 8345, 'la': 3936, 'buffet': 950, 'cine': 1284, 'there': 7403, 'got': 2930, 'amore': 249, 'wat': 8091, 'ok': 5090, 'lar': 3972, 'joking': 3748, 'wif': 8234, 'oni': 5124, 'free': 2656, 'entry': 2237, 'wkly': 8296, 'comp': 1400, 'to': 7533, 'win': 8249, 'fa': 2373, 'cup': 1625, 'final': 2500, 'tkts': 7522, 'st': 6911, 'may': 4419, 'text': 7344, 'receive': 5956, 'questionstd': 5846, 'txt': 7736, 'ratetcs': 5899, 'apply': 341, 'overs': 5233, 'dun': 2087, 'say': 6310, 'so': 6730, 'early': 2109, 'hor': 3312, 'already': 221, 'then': 7397, 'nah': 4784, 'dont': 1993, 'think': 7427, 'he': 3131, 'goes': 2886, 'usf': 7891, 'lives': 4140, 'around': 392, 'here': 3187, 'though': 7450, 'freemsg': 2664, 'hey': 3206, 'darling': 1688, 'its': 3651, 'been': 654, 'weeks': 8149, 'now': 4983, 'and': 266, 'no': 4921, 'word': 8331, 'back': 536, 'id': 3433, 'l

8603

In [18]:
#max_features = len(voc) # 8603
max_features = 4000  
'''
max_features = 4000 : 절반 단어를 이용해서 분석  
'''

'\nmax_features = 4000 : 절반 단어를 이용해서 분석  \n'

In [20]:
# 4. sparse matrix
tfidf = TfidfVectorizer(max_features=max_features, stop_words='english')
sparse_mat = tfidf.fit_transform(texts) # stances -> sparse matrix
print(sparse_mat.shape) # (5574, 8336) -> (5574, 4000)
print(sparse_mat)

(5574, 4000)
  (0, 3787)	0.23028059868952055
  (0, 1285)	0.1893428233646285
  (0, 550)	0.3411906679200504
  (0, 395)	0.38553507725150876
  (0, 1695)	0.3311020934319133
  (0, 3896)	0.27851471854901527
  (0, 1299)	0.22479373591163246
  (0, 396)	0.3411906679200504
  (0, 190)	0.30711178492950625
  (0, 685)	0.31277055339233667
  (0, 2388)	0.3158897998103812
  (1, 2223)	0.5462886514993854
  (1, 3842)	0.43136967121190617
  (1, 1616)	0.523359885891641
  (1, 1710)	0.4080813026646178
  (1, 2211)	0.2739580191499278
  (2, 2254)	0.2531701882587318
  (2, 137)	0.18197931131431813
  (2, 2692)	0.2531701882587318
  (2, 3630)	0.13605302813478945
  (2, 2644)	0.2531701882587318
  (2, 2743)	0.1802324014955286
  (2, 3470)	0.13296332314310053
  (2, 3282)	0.1696431141604461
  (2, 3534)	0.2380043365494792
  :	:
  (5569, 1994)	0.33240559958166266
  (5569, 642)	0.2703206897791868
  (5569, 3524)	0.21747118795699225
  (5569, 3601)	0.3253987454590034
  (5569, 2121)	0.30729962773407055
  (5569, 3882)	0.26681337143010

In [22]:
arr_sparse_mat = sparse_mat.toarray()
print(arr_sparse_mat,"\n")

print(arr_sparse_mat[:20, 100:150])
arr_sparse_mat.shape # (5574, 4000)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.

(5574, 4000)

In [24]:
# 5. train/test split 
from sklearn.model_selection import train_test_split
train_texts, test_texts, train_target, test_target = train_test_split(arr_sparse_mat, target, test_size = 0.3)

print(train_texts.shape) # (3901, 4000)
print(test_texts.shape) # (1673, 4000)

(3901, 4000)
(1673, 4000)


In [26]:
# 6. pickle file save 
import numpy as np 

spam_train_test = (train_texts,test_texts,train_target ,test_target )  # 튜플로 묵어줌
np.save("C:/Users/hyebin/Desktop/lee/Machine Learning_Study/data/spam_train_test.npy",spam_train_test )

C:\Users\hyebin\anaconda3\lib\site-packages\numpy\core\_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)


In [28]:
train_texts,test_texts,train_target,test_target = np.load("C:/Users/hyebin/Desktop/lee/Machine Learning_Study/data/spam_train_test.npy",allow_pickle=True) 